const state = {
  currentDate: new Date(),
  view: "month",
  activeTab: "calendar",
  selectedPersonId: "family",
  roomId: "",
  lastUpdatedAt: 0,
  members: [],
  events: [],
  requests: [],
  todos: [],
  chores: [],
  planner: {
    location: "",
    prefs: "",
    partnerEmail: "",
    ideas: [],
  },
};

const DAY_NAMES = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
let syncTimer = null;

const el = {
  label: document.getElementById("currentLabel"),
  grid: document.getElementById("calendarGrid"),
  viewBtns: document.querySelectorAll(".view-btn"),
  mainTabs: document.querySelectorAll("#mainTabs .tab-btn"),
  personTabs: document.getElementById("personTabs"),
  calendarPage: document.getElementById("calendarPage"),
  requestsPage: document.getElementById("requestsPage"),
  choresPage: document.getElementById("choresPage"),
  plannerPage: document.getElementById("plannerPage"),
  requestList: document.getElementById("requestList"),
  recurringList: document.getElementById("recurringList"),
  memberList: document.getElementById("memberList"),
  choreList: document.getElementById("choreList"),
  personEvents: document.getElementById("personEvents"),
  plannerIdeas: document.getElementById("plannerIdeas"),
  plannerLocation: document.getElementById("plannerLocation"),
  plannerPrefs: document.getElementById("plannerPrefs"),
  partnerEmail: document.getElementById("partnerEmail"),
  choreGenNote: document.getElementById("choreGenNote"),
  eventMember: document.getElementById("eventMember"),
  requestMember: document.getElementById("requestMember"),
  choreMember: document.getElementById("choreMember"),
  icalMember: document.getElementById("icalMember"),
  eventAllDay: document.getElementById("eventAllDay"),
  eventTimeRow: document.getElementById("eventTimeRow"),
  eventInvolved: document.getElementById("eventInvolved"),
};

function uid() {
  return `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

function newRoomId() {
  return Math.random().toString(36).slice(2, 10);
}

function formatDate(d) {
  return d.toISOString().slice(0, 10);
}

function addDaysIso(iso, days) {
  const d = new Date(`${iso}T00:00:00`);
  d.setDate(d.getDate() + days);
  return formatDate(d);
}

function memberColor(memberName) {
  const input = (memberName || "family").toLowerCase();
  let hash = 0;
  for (let i = 0; i < input.length; i += 1) hash = ((hash << 5) - hash + input.charCodeAt(i)) | 0;
  const hue = Math.abs(hash) % 360;
  return `hsl(${hue} 70% 45%)`;
}

function defaultMembers() {
  return [
    { id: uid(), name: "Adult 1", role: "adult", age: 35, gender: "woman" },
    { id: uid(), name: "Adult 2", role: "adult", age: 36, gender: "man" },
    { id: uid(), name: "Kid 1", role: "child", age: 12, gender: "non-binary" },
    { id: uid(), name: "Kid 2", role: "child", age: 10, gender: "non-binary" },
    { id: uid(), name: "Kid 3", role: "child", age: 8, gender: "non-binary" },
    { id: uid(), name: "Kid 4", role: "child", age: 6, gender: "non-binary" },
  ];
}

function normalizeMember(m) {
  return {
    id: m.id || uid(),
    name: m.name || "Unnamed",
    role: m.role === "adult" ? "adult" : "child",
    age: Number(m.age) || 0,
    gender: m.gender || "non-binary",
  };
}

function normalizeEvent(ev) {
  return {
    id: ev.id || uid(),
    title: ev.title || "Untitled",
    startDate: ev.startDate || ev.date || "",
    endDate: ev.endDate || ev.startDate || ev.date || "",
    allDay: !!ev.allDay,
    start: ev.start || "",
    end: ev.end || "",
    memberId: ev.memberId || "",
    memberName: ev.memberName || ev.member || "",
    involvedMemberIds: Array.isArray(ev.involvedMemberIds) ? ev.involvedMemberIds : [],
    recurring: ev.recurring || "none",
  };
}

function normalizeRequest(r) {
  return {
    id: r.id || uid(),
    text: r.text || "",
    memberId: r.memberId || "",
    memberName: r.memberName || r.member || "",
  };
}

function normalizeChore(c) {
  return {
    id: c.id || uid(),
    title: c.title || "",
    frequency: c.frequency || "Daily",
    done: !!c.done,
    autogenerated: !!c.autogenerated,
    memberId: c.memberId || "",
    memberName: c.memberName || c.member || "",
  };
}

function normalizePayload(p) {
  return {
    members: (Array.isArray(p.members) ? p.members : []).map(normalizeMember),
    events: (Array.isArray(p.events) ? p.events : []).map(normalizeEvent),
    requests: (Array.isArray(p.requests) ? p.requests : []).map(normalizeRequest),
    chores: (Array.isArray(p.chores) ? p.chores : []).map(normalizeChore),
    selectedPersonId: typeof p.selectedPersonId === "string" ? p.selectedPersonId : "family",
    activeTab: ["calendar", "requests", "chores", "planner"].includes(p.activeTab) ? p.activeTab : "calendar",
    planner: {
      location: p.planner?.location || "",
      prefs: p.planner?.prefs || "",
      partnerEmail: p.planner?.partnerEmail || "",
      ideas: Array.isArray(p.planner?.ideas) ? p.planner.ideas : [],
    },
    lastUpdatedAt: Number(p.lastUpdatedAt) || 0,
  };
}

function applyLoadedState(raw) {
  const p = normalizePayload(raw || {});
  state.members = p.members.length ? p.members : defaultMembers();
  state.events = p.events;
  state.requests = p.requests;
  state.chores = p.chores;
  state.selectedPersonId = p.selectedPersonId;
  state.activeTab = p.activeTab;
  state.planner = p.planner;
  state.lastUpdatedAt = p.lastUpdatedAt;
  backfillLinks();

  if (state.selectedPersonId !== "family" && !findMember(state.selectedPersonId)) {
    state.selectedPersonId = "family";
  }
}

function serializeState() {
  return {
    members: state.members,
    events: state.events,
    requests: state.requests,
    chores: state.chores,
    selectedPersonId: state.selectedPersonId,
    activeTab: state.activeTab,
    planner: state.planner,
    lastUpdatedAt: state.lastUpdatedAt,
  };
}

function saveLocal() {
  localStorage.setItem("familyCalendarState", JSON.stringify(serializeState()));
}

function touch() {
  state.lastUpdatedAt = Date.now();
}

async function pushRemote() {
  if (!state.roomId) return;
  try {
    await fetch(`/api/state?room=${encodeURIComponent(state.roomId)}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(serializeState()),
    });
  } catch (_err) {}
}

async function saveState() {
  touch();
  saveLocal();
  await pushRemote();
}

async function fetchRemote() {
  if (!state.roomId) return null;
  try {
    const r = await fetch(`/api/state?room=${encodeURIComponent(state.roomId)}`);
    if (!r.ok) return null;
    return await r.json();
  } catch (_err) {
    return null;
  }
}

async function mergeRemoteIfNewer() {
  const remote = await fetchRemote();
  if (!remote || Number(remote.lastUpdatedAt) <= state.lastUpdatedAt) return;
  applyLoadedState(remote);
  saveLocal();
  render();
}

function startPolling() {
  if (!state.roomId) return;
  if (syncTimer) clearInterval(syncTimer);
  syncTimer = setInterval(() => mergeRemoteIfNewer(), 5000);
}

async function loadState() {
  const url = new URL(window.location.href);
  const room = url.searchParams.get("room");
  const data = url.searchParams.get("data");
  if (room) state.roomId = room;

  if (data) {
    try { applyLoadedState(JSON.parse(decodeURIComponent(atob(data)))); } catch (_err) {}
  }

  const local = localStorage.getItem("familyCalendarState");
  if (local) {
    try {
      const parsed = JSON.parse(local);
      const n = normalizePayload(parsed);
      if (n.lastUpdatedAt >= state.lastUpdatedAt) applyLoadedState(parsed);
    } catch (_err) {}
  }

  if (state.roomId) {
    const remote = await fetchRemote();
    if (remote && Number(remote.lastUpdatedAt) > state.lastUpdatedAt) {
      applyLoadedState(remote);
    } else if (!remote && state.lastUpdatedAt) {
      await pushRemote();
    }
  }

  if (!state.members.length) state.members = defaultMembers();
  saveLocal();
  startPolling();
}

function findMember(id) {
  return state.members.find((m) => m.id === id) || null;
}

function findMemberByName(name) {
  if (!name) return null;
  const n = name.trim().toLowerCase();
  return state.members.find((m) => m.name.trim().toLowerCase() === n) || null;
}

function displayMember(item) {
  if (item.memberId) {
    const m = findMember(item.memberId);
    if (m) return m.name;
  }
  return item.memberName || "Unassigned";
}

function backfillLinks() {
  for (const collection of [state.events, state.requests, state.chores]) {
    for (const row of collection) {
      if (!row.memberId && row.memberName) {
        const m = findMemberByName(row.memberName);
        if (m) row.memberId = m.id;
      }
      if (row.memberId && !row.memberName) {
        const m = findMember(row.memberId);
        if (m) row.memberName = m.name;
      }
    }
  }
}

function matchesSelected(item) {
  if (state.selectedPersonId === "family") return true;
  if (item.memberId === state.selectedPersonId) return true;
  if (Array.isArray(item.involvedMemberIds) && item.involvedMemberIds.includes(state.selectedPersonId)) return true;
  return false;
}

function visibleEvents() { return state.events.filter(matchesSelected); }
function visibleRequests() { return state.requests.filter(matchesSelected); }
function visibleChores() { return state.chores.filter(matchesSelected); }

function setMainTab(tab, save = true) {
  state.activeTab = tab;
  el.mainTabs.forEach((b) => b.classList.toggle("active", b.dataset.tab === tab));
  el.calendarPage.classList.toggle("active", tab === "calendar");
  el.requestsPage.classList.toggle("active", tab === "requests");
  el.choresPage.classList.toggle("active", tab === "chores");
  el.plannerPage.classList.toggle("active", tab === "planner");
  if (save) saveState();
}

function setSelectedPerson(id, save = true) {
  state.selectedPersonId = id;
  renderPersonTabs();
  populateMemberSelects();
  renderCalendar();
  renderRequests();
  renderRecurring();
  renderPersonEvents();
  renderChores();
  updateChoreNote();
  if (save) saveState();
}

function renderPersonTabs() {
  const items = [
    `<button class="person-tab ${state.selectedPersonId === "family" ? "active" : ""}" data-person-id="family">Family</button>`,
    ...state.members.map((m) => `<button class="person-tab ${state.selectedPersonId === m.id ? "active" : ""}" data-person-id="${m.id}">${escapeHtml(m.name)}</button>`),
  ];
  el.personTabs.innerHTML = items.join("");
}

function renderInvolvedChecklist() {
  el.eventInvolved.innerHTML = state.members.map((m) => `
    <label class="checkbox-row">
      <input type="checkbox" value="${m.id}" data-involved-member />
      <span>${escapeHtml(m.name)}</span>
    </label>
  `).join("");
}

function populateMemberSelects() {
  const selects = [el.eventMember, el.requestMember, el.choreMember, el.icalMember];
  const selected = state.selectedPersonId !== "family" ? state.selectedPersonId : state.members[0]?.id;
  for (const s of selects) {
    s.innerHTML = state.members.map((m) => `<option value="${m.id}">${escapeHtml(m.name)}</option>`).join("");
    if (selected) s.value = selected;
  }
}

function setView(view) {
  state.view = view;
  el.viewBtns.forEach((b) => b.classList.toggle("active", b.dataset.view === view));
  renderCalendar();
}

function shiftDate(direction) {
  const d = new Date(state.currentDate);
  if (state.view === "day") d.setDate(d.getDate() + direction);
  if (state.view === "week") d.setDate(d.getDate() + direction * 7);
  if (state.view === "month") d.setMonth(d.getMonth() + direction);
  if (state.view === "year") d.setFullYear(d.getFullYear() + direction);
  state.currentDate = d;
  renderCalendar();
}

function getWeekStart(date) {
  const d = new Date(date);
  d.setDate(d.getDate() - d.getDay());
  d.setHours(0, 0, 0, 0);
  return d;
}

function occursOnDate(ev, dateObj, targetIso) {
  if (!ev.startDate) return false;
  const end = ev.endDate || ev.startDate;
  if (ev.recurring === "none") return targetIso >= ev.startDate && targetIso <= end;
  const origin = new Date(`${ev.startDate}T00:00:00`);
  if (dateObj < origin) return false;
  if (ev.recurring === "daily") return true;
  if (ev.recurring === "weekly") return origin.getDay() === dateObj.getDay();
  if (ev.recurring === "monthly") return origin.getDate() === dateObj.getDate();
  return false;
}

function eventsForDate(dateObj) {
  const iso = formatDate(dateObj);
  return visibleEvents().filter((ev) => occursOnDate(ev, dateObj, iso));
}

function eventDateText(ev) {
  if (!ev.startDate) return "";
  if (ev.startDate === ev.endDate) return ev.startDate;
  return `${ev.startDate} to ${ev.endDate}`;
}

function eventInvolvedNames(ev) {
  const ids = Array.isArray(ev.involvedMemberIds) ? ev.involvedMemberIds : [];
  const names = ids.map((id) => findMember(id)?.name).filter(Boolean);
  return names;
}

function dateCell(date, includeDayChores = false) {
  const iso = formatDate(date);
  const rows = eventsForDate(date).map((ev) => {
    const owner = displayMember(ev);
    const involved = eventInvolvedNames(ev);
    const involvedText = involved.length ? `<div class="event-meta">Involved: ${escapeHtml(involved.join(", "))}</div>` : "";
    return `
      <li class="event-item" style="--member-color: ${memberColor(owner)}">
        <div>
          <strong>${ev.allDay ? "All Day " : (ev.start ? `${ev.start} ` : "")}${escapeHtml(ev.title)}</strong>
          <div class="event-meta">${escapeHtml(eventDateText(ev))}${ev.recurring !== "none" ? ` | ${escapeHtml(ev.recurring)}` : ""}</div>
          ${involvedText}
        </div>
        <span class="member-pill" style="--member-color: ${memberColor(owner)}">${escapeHtml(owner)}</span>
      </li>
    `;
  }).join("");

  const choresBlock = includeDayChores
    ? `<div class="day-chores"><h4>Chores</h4><ul>${visibleChores().map((c) => `<li><label><input type="checkbox" data-toggle-chore="${c.id}" ${c.done ? "checked" : ""} /><span class="${c.done ? "done" : ""}">${escapeHtml(c.title)} <small>(${escapeHtml(c.frequency)})</small></span></label></li>`).join("") || "<li class='muted'>No chores</li>"}</ul></div>`
    : "";

  return `
    <article class="cell">
      <h4>${DAY_NAMES[date.getDay()]} ${date.getMonth() + 1}/${date.getDate()}</h4>
      <ul>${rows || "<li class='muted'>No events</li>"}</ul>
      ${choresBlock}
      <button class="link-btn" data-action="jump" data-date="${iso}">Add here</button>
    </article>
  `;
}

function renderCalendar() {
  const d = new Date(state.currentDate);
  const who = state.selectedPersonId === "family" ? "Family" : (findMember(state.selectedPersonId)?.name || "Family");

  if (state.view === "day") {
    el.label.textContent = `${who} | ${d.toLocaleDateString(undefined, { weekday: "long", month: "long", day: "numeric", year: "numeric" })}`;
    el.grid.className = "calendar-grid day";
    el.grid.innerHTML = dateCell(d, true);
    return;
  }

  if (state.view === "week") {
    const start = getWeekStart(d);
    const days = Array.from({ length: 7 }, (_, i) => {
      const x = new Date(start);
      x.setDate(start.getDate() + i);
      return x;
    });
    const end = days[6];
    el.label.textContent = `${who} | ${start.toLocaleDateString()} - ${end.toLocaleDateString()}`;
    el.grid.className = "calendar-grid week";
    el.grid.innerHTML = days.map((x) => dateCell(x)).join("");
    return;
  }

  if (state.view === "month") {
    const monthStart = new Date(d.getFullYear(), d.getMonth(), 1);
    const start = getWeekStart(monthStart);
    const days = Array.from({ length: 42 }, (_, i) => {
      const x = new Date(start);
      x.setDate(start.getDate() + i);
      return x;
    });
    el.label.textContent = `${who} | ${d.toLocaleDateString(undefined, { month: "long", year: "numeric" })}`;
    el.grid.className = "calendar-grid month";
    el.grid.innerHTML = days.map((x) => `<div class="month-cell ${x.getMonth() !== d.getMonth() ? "faded" : ""}">${dateCell(x)}</div>`).join("");
    return;
  }

  const year = d.getFullYear();
  el.label.textContent = `${who} | ${year}`;
  el.grid.className = "calendar-grid year";
  el.grid.innerHTML = Array.from({ length: 12 }, (_, m) => {
    const first = new Date(year, m, 1);
    const daysInMonth = new Date(year, m + 1, 0).getDate();
    let count = 0;
    for (let day = 1; day <= daysInMonth; day += 1) {
      const date = new Date(year, m, day);
      count += eventsForDate(date).length;
    }
    return `<article class="cell month-summary"><h4>${first.toLocaleDateString(undefined, { month: "long" })}</h4><p>${count} event${count === 1 ? "" : "s"}</p></article>`;
  }).join("");
}

function renderRequests() {
  const rows = visibleRequests().map((r) => {
    const who = displayMember(r);
    return `<li><div class="list-content"><span>${escapeHtml(r.text)}</span><span class="member-pill" style="--member-color:${memberColor(who)}">${escapeHtml(who)}</span></div><button class="icon-btn" data-delete-request="${r.id}">✕</button></li>`;
  }).join("");
  el.requestList.innerHTML = rows || "<li class='muted'>No requests yet.</li>";
}

function renderRecurring() {
  const rows = visibleEvents().filter((e) => e.recurring !== "none").map((ev) => {
    const who = displayMember(ev);
    return `<li><div class="list-content"><span>${escapeHtml(ev.title)} <small>(${escapeHtml(ev.recurring)})</small></span><span class="member-pill" style="--member-color:${memberColor(who)}">${escapeHtml(who)}</span></div><button class="icon-btn" data-remove-recurring="${ev.id}">✕</button></li>`;
  }).join("");
  el.recurringList.innerHTML = rows || "<li class='muted'>No recurring activities.</li>";
}

function renderMemberList() {
  el.memberList.innerHTML = state.members.map((m) => `
    <li>
      <div class="list-content"><strong>${escapeHtml(m.name)}</strong><small>${escapeHtml(m.role)} | age ${m.age}</small></div>
      <div class="row-actions"><button class="btn btn-secondary" data-rename-member="${m.id}">Rename</button><button class="icon-btn" data-delete-member="${m.id}">✕</button></div>
    </li>
  `).join("");
}

function renderPersonEvents() {
  const upcoming = visibleEvents()
    .slice()
    .sort((a, b) => `${a.startDate}${a.start}`.localeCompare(`${b.startDate}${b.start}`))
    .slice(0, 12);
  el.personEvents.innerHTML = upcoming.map((ev) => {
    const who = displayMember(ev);
    return `<li><div class="list-content"><strong>${escapeHtml(ev.title)}</strong><small>${escapeHtml(ev.startDate)}${ev.allDay ? " (All Day)" : (ev.start ? ` ${escapeHtml(ev.start)}` : "")}</small></div><span class="member-pill" style="--member-color:${memberColor(who)}">${escapeHtml(who)}</span></li>`;
  }).join("") || "<li class='muted'>No upcoming activities for this view.</li>";
}

function renderChores() {
  el.choreList.innerHTML = visibleChores().map((c) => {
    const who = displayMember(c);
    return `<li><div class="list-content"><label><input type="checkbox" data-toggle-chore="${c.id}" ${c.done ? "checked" : ""} /><span class="${c.done ? "done" : ""}">${escapeHtml(c.title)} <small>(${escapeHtml(c.frequency)})</small></span></label><span class="member-pill" style="--member-color:${memberColor(who)}">${escapeHtml(who)}</span></div><button class="icon-btn" data-delete-chore="${c.id}">✕</button></li>`;
  }).join("") || "<li class='muted'>No chores for this view.</li>";
}

function updateChoreNote() {
  const m = findMember(state.selectedPersonId);
  el.choreGenNote.textContent = m ? `Generate chores for ${m.name}.` : "Select a person tab to generate chores.";
}

function generatedChoresFor(member) {
  const base = member.role === "adult"
    ? [
        { title: "Kitchen cleanup", frequency: "Daily" },
        { title: "Laundry cycle", frequency: "Weekly" },
        { title: "Trash and recycling", frequency: "Weekly" },
      ]
    : member.age <= 8
      ? [
          { title: "Make bed", frequency: "Daily" },
          { title: "Put toys away", frequency: "Daily" },
          { title: "Sort laundry", frequency: "Weekly" },
        ]
      : [
          { title: "Tidy room", frequency: "Daily" },
          { title: "Dishwasher help", frequency: "Daily" },
          { title: "Vacuum room", frequency: "Weekly" },
        ];

  return base.map((t) => ({
    id: uid(),
    title: t.title,
    frequency: t.frequency,
    done: false,
    autogenerated: true,
    memberId: member.id,
    memberName: member.name,
  }));
}

function setPlannerInputs() {
  el.plannerLocation.value = state.planner.location || "";
  el.plannerPrefs.value = state.planner.prefs || "";
  el.partnerEmail.value = state.planner.partnerEmail || "";
}

function renderPlannerIdeas() {
  const rows = state.planner.ideas.map((idea, i) => {
    return `
      <li>
        <div class="list-content">
          <strong>${escapeHtml(idea.title || "Date Idea")}</strong>
          <small>${escapeHtml(idea.date || "")} ${escapeHtml(idea.start_time || "")} - ${escapeHtml(idea.end_time || "")}</small>
          <small>${escapeHtml(idea.place || "")}</small>
          <small>${escapeHtml(idea.notes || "")}</small>
        </div>
        <button class="btn btn-secondary" data-choose-idea="${i}">Choose</button>
      </li>
    `;
  }).join("");
  el.plannerIdeas.innerHTML = rows || "<li class='muted'>No ideas yet. Generate suggestions.</li>";
}

async function requestDateIdeas() {
  const payload = {
    location: el.plannerLocation.value.trim(),
    preferences: el.plannerPrefs.value.trim(),
    existingEvents: state.events.map((e) => ({
      title: e.title,
      startDate: e.startDate,
      endDate: e.endDate,
      allDay: e.allDay,
      start: e.start,
      end: e.end,
    })),
  };

  const r = await fetch("/api/date-ideas", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  });

  if (!r.ok) throw new Error("Date ideas request failed");
  return r.json();
}

function parseIcalLines(text) {
  const raw = text.replace(/\r\n/g, "\n").replace(/\r/g, "\n").split("\n");
  const lines = [];
  for (const ln of raw) {
    if ((ln.startsWith(" ") || ln.startsWith("\t")) && lines.length) lines[lines.length - 1] += ln.slice(1);
    else lines.push(ln);
  }
  return lines;
}

function parseIcalDate(value) {
  if (!/^\d{8}$/.test(value)) return "";
  return `${value.slice(0, 4)}-${value.slice(4, 6)}-${value.slice(6, 8)}`;
}

function parseIcalDateTime(value) {
  const m = value.match(/^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})?Z?$/);
  if (!m) return { date: "", time: "" };
  const y = Number(m[1]);
  const mo = Number(m[2]) - 1;
  const d = Number(m[3]);
  const h = Number(m[4]);
  const mi = Number(m[5]);
  const sec = Number(m[6] || 0);
  const z = value.endsWith("Z");
  const dt = z ? new Date(Date.UTC(y, mo, d, h, mi, sec)) : new Date(y, mo, d, h, mi, sec);
  return { date: formatDate(dt), time: `${String(dt.getHours()).padStart(2, "0")}:${String(dt.getMinutes()).padStart(2, "0")}` };
}

function parseIcal(text) {
  const lines = parseIcalLines(text);
  const out = [];
  let cur = null;

  for (const line of lines) {
    if (line === "BEGIN:VEVENT") { cur = {}; continue; }
    if (line === "END:VEVENT") { if (cur) out.push(cur); cur = null; continue; }
    if (!cur || !line.includes(":")) continue;
    const idx = line.indexOf(":");
    const left = line.slice(0, idx);
    const value = line.slice(idx + 1);
    const [key, ...params] = left.split(";");
    cur[key.toUpperCase()] = { value, params: params.join(";").toUpperCase() };
  }

  return out.map((e) => {
    const summary = e.SUMMARY?.value || "Imported Event";
    const start = e.DTSTART?.value || "";
    const end = e.DTEND?.value || "";
    const startDateOnly = e.DTSTART?.params?.includes("VALUE=DATE") || /^\d{8}$/.test(start);
    const endDateOnly = e.DTEND?.params?.includes("VALUE=DATE") || /^\d{8}$/.test(end);
    const rrule = e.RRULE?.value || "";

    let startDate = "";
    let endDate = "";
    let startTime = "";
    let endTime = "";

    if (startDateOnly) {
      startDate = parseIcalDate(start);
      endDate = end ? parseIcalDate(end) : startDate;
      if (end && endDateOnly) endDate = addDaysIso(endDate, -1);
    } else {
      const s = parseIcalDateTime(start);
      const x = end ? parseIcalDateTime(end) : s;
      startDate = s.date;
      endDate = x.date || s.date;
      startTime = s.time;
      endTime = x.time;
    }

    let recurring = "none";
    const freq = rrule.match(/FREQ=([A-Z]+)/)?.[1] || "";
    if (freq === "DAILY") recurring = "daily";
    if (freq === "WEEKLY") recurring = "weekly";
    if (freq === "MONTHLY") recurring = "monthly";

    return { title: summary, startDate, endDate: endDate || startDate, start: startTime, end: endTime, recurring, allDay: !startTime && !endTime };
  }).filter((x) => x.startDate);
}

function escapeIcal(s) {
  return String(s || "").replace(/\\/g, "\\\\").replace(/\n/g, "\\n").replace(/,/g, "\\,").replace(/;/g, "\\;");
}

function toIcalDate(iso) { return iso.replace(/-/g, ""); }
function toIcalDateTime(iso, t) {
  const hh = (t || "00:00").slice(0, 2);
  const mm = (t || "00:00").slice(3, 5);
  return `${toIcalDate(iso)}T${hh}${mm}00`;
}

function exportIcal(rows) {
  const now = new Date();
  const stamp = `${now.getUTCFullYear()}${String(now.getUTCMonth() + 1).padStart(2, "0")}${String(now.getUTCDate()).padStart(2, "0")}T${String(now.getUTCHours()).padStart(2, "0")}${String(now.getUTCMinutes()).padStart(2, "0")}${String(now.getUTCSeconds()).padStart(2, "0")}Z`;
  const lines = ["BEGIN:VCALENDAR", "VERSION:2.0", "PRODID:-//FamCal//EN", "CALSCALE:GREGORIAN"];

  for (const ev of rows) {
    lines.push("BEGIN:VEVENT");
    lines.push(`UID:${ev.id}@famcal.local`);
    lines.push(`DTSTAMP:${stamp}`);
    if (ev.allDay) {
      lines.push(`DTSTART;VALUE=DATE:${toIcalDate(ev.startDate)}`);
      lines.push(`DTEND;VALUE=DATE:${toIcalDate(addDaysIso(ev.endDate || ev.startDate, 1))}`);
    } else {
      lines.push(`DTSTART:${toIcalDateTime(ev.startDate, ev.start || "09:00")}`);
      lines.push(`DTEND:${toIcalDateTime(ev.endDate || ev.startDate, ev.end || ev.start || "10:00")}`);
    }
    if (ev.recurring === "daily") lines.push("RRULE:FREQ=DAILY");
    if (ev.recurring === "weekly") lines.push("RRULE:FREQ=WEEKLY");
    if (ev.recurring === "monthly") lines.push("RRULE:FREQ=MONTHLY");
    lines.push(`SUMMARY:${escapeIcal(ev.title)}`);
    lines.push("END:VEVENT");
  }
  lines.push("END:VCALENDAR");
  return lines.join("\r\n");
}

function escapeHtml(str) {
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function selectedMemberFrom(select) {
  return findMember(select.value) || state.members[0] || null;
}

document.getElementById("eventAllDay").addEventListener("change", () => {
  el.eventTimeRow.classList.toggle("hidden", el.eventAllDay.checked);
});

document.getElementById("eventForm").addEventListener("submit", async (e) => {
  e.preventDefault();
  const title = document.getElementById("eventTitle").value.trim();
  const startDate = document.getElementById("eventStartDate").value;
  const endDateRaw = document.getElementById("eventEndDate").value;
  const allDay = el.eventAllDay.checked;
  const owner = selectedMemberFrom(el.eventMember);
  const involved = Array.from(document.querySelectorAll("[data-involved-member]:checked")).map((x) => x.value);
  if (!title || !startDate || !endDateRaw || !owner) return;

  state.events.push({
    id: uid(),
    title,
    startDate,
    endDate: endDateRaw < startDate ? startDate : endDateRaw,
    allDay,
    start: allDay ? "" : document.getElementById("eventStart").value,
    end: allDay ? "" : document.getElementById("eventEnd").value,
    memberId: owner.id,
    memberName: owner.name,
    involvedMemberIds: Array.from(new Set(involved.concat(owner.id))),
    recurring: document.getElementById("eventRecurring").value,
  });

  e.target.reset();
  el.eventTimeRow.classList.remove("hidden");
  renderInvolvedChecklist();
  populateMemberSelects();
  await saveState();
  renderCalendar();
  renderRecurring();
  renderPersonEvents();
});

document.getElementById("requestForm").addEventListener("submit", async (e) => {
  e.preventDefault();
  const text = document.getElementById("requestInput").value.trim();
  const member = selectedMemberFrom(el.requestMember);
  if (!text || !member) return;
  state.requests.unshift({ id: uid(), text, memberId: member.id, memberName: member.name });
  e.target.reset();
  populateMemberSelects();
  await saveState();
  renderRequests();
});

document.getElementById("memberForm").addEventListener("submit", async (e) => {
  e.preventDefault();
  const name = document.getElementById("memberName").value.trim();
  const role = document.getElementById("memberRole").value;
  const age = Number(document.getElementById("memberAge").value);
  const gender = document.getElementById("memberGender").value;
  if (!name || !role || !age || !gender) return;
  state.members.push({ id: uid(), name, role, age, gender });
  e.target.reset();
  await saveState();
  renderPersonTabs();
  populateMemberSelects();
  renderInvolvedChecklist();
  renderMemberList();
});

document.getElementById("choreForm").addEventListener("submit", async (e) => {
  e.preventDefault();
  const title = document.getElementById("choreInput").value.trim();
  const frequency = document.getElementById("choreFrequency").value;
  const member = selectedMemberFrom(el.choreMember);
  if (!title || !member) return;

  state.chores.unshift({
    id: uid(),
    title,
    frequency,
    done: false,
    autogenerated: false,
    memberId: member.id,
    memberName: member.name,
  });
  e.target.reset();
  populateMemberSelects();
  await saveState();
  renderChores();
});

document.getElementById("generateChoresBtn").addEventListener("click", async () => {
  const member = findMember(state.selectedPersonId);
  if (!member) {
    alert("Select a person tab first.");
    return;
  }
  state.chores = state.chores.filter((c) => !(c.memberId === member.id && c.autogenerated));
  state.chores.unshift(...generatedChoresFor(member));
  await saveState();
  renderChores();
});

document.getElementById("plannerForm").addEventListener("submit", async (e) => {
  e.preventDefault();
  state.planner.location = el.plannerLocation.value.trim();
  state.planner.prefs = el.plannerPrefs.value.trim();
  state.planner.partnerEmail = el.partnerEmail.value.trim();
  el.plannerIdeas.innerHTML = "<li>Generating ideas...</li>";

  try {
    const data = await requestDateIdeas();
    state.planner.ideas = Array.isArray(data.ideas) ? data.ideas : [];
  } catch (_err) {
    state.planner.ideas = [];
    el.plannerIdeas.innerHTML = "<li>Could not generate ideas right now. Check OpenAI config.</li>";
    await saveState();
    return;
  }

  await saveState();
  renderPlannerIdeas();
});

document.getElementById("icalForm").addEventListener("submit", async (e) => {
  e.preventDefault();
  const file = document.getElementById("icalFile").files?.[0];
  const member = selectedMemberFrom(el.icalMember);
  if (!file || !member) return;
  const text = await file.text();
  const incoming = parseIcal(text);
  let merged = 0;

  for (const ev of incoming) {
    const exists = state.events.some((x) => x.memberId === member.id && x.title === ev.title && x.startDate === ev.startDate && (x.start || "") === (ev.start || ""));
    if (exists) continue;
    state.events.push({
      id: uid(),
      title: ev.title,
      startDate: ev.startDate,
      endDate: ev.endDate,
      allDay: ev.allDay,
      start: ev.start,
      end: ev.end,
      memberId: member.id,
      memberName: member.name,
      involvedMemberIds: [member.id],
      recurring: ev.recurring,
    });
    merged += 1;
  }

  await saveState();
  renderCalendar();
  renderRecurring();
  renderPersonEvents();
  document.getElementById("icalFile").value = "";
  alert(`Merged ${merged} event${merged === 1 ? "" : "s"}.`);
});

document.getElementById("exportIcalBtn").addEventListener("click", () => {
  const rows = visibleEvents();
  const text = exportIcal(rows);
  const blob = new Blob([text], { type: "text/calendar;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `famcal-${formatDate(new Date())}.ics`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
});

el.requestList.addEventListener("click", async (e) => {
  const id = e.target.dataset.deleteRequest;
  if (!id) return;
  state.requests = state.requests.filter((r) => r.id !== id);
  await saveState();
  renderRequests();
});

el.recurringList.addEventListener("click", async (e) => {
  const id = e.target.dataset.removeRecurring;
  if (!id) return;
  state.events = state.events.filter((ev) => ev.id !== id);
  await saveState();
  renderCalendar();
  renderRecurring();
  renderPersonEvents();
});

el.memberList.addEventListener("click", async (e) => {
  const renameId = e.target.dataset.renameMember;
  if (renameId) {
    const m = findMember(renameId);
    if (!m) return;
    const next = prompt("New name:", m.name);
    if (!next || !next.trim()) return;
    m.name = next.trim();
    for (const set of [state.events, state.requests, state.chores]) {
      for (const item of set) if (item.memberId === m.id) item.memberName = m.name;
    }
    await saveState();
    render();
    return;
  }

  const deleteId = e.target.dataset.deleteMember;
  if (!deleteId) return;
  if (state.members.length <= 1) {
    alert("Keep at least one member.");
    return;
  }

  state.members = state.members.filter((m) => m.id !== deleteId);
  state.events = state.events.filter((x) => x.memberId !== deleteId).map((x) => ({ ...x, involvedMemberIds: (x.involvedMemberIds || []).filter((id) => id !== deleteId) }));
  state.requests = state.requests.filter((x) => x.memberId !== deleteId);
  state.chores = state.chores.filter((x) => x.memberId !== deleteId);
  if (state.selectedPersonId === deleteId) state.selectedPersonId = "family";

  await saveState();
  render();
});

el.choreList.addEventListener("click", async (e) => {
  const id = e.target.dataset.deleteChore;
  if (!id) return;
  state.chores = state.chores.filter((c) => c.id !== id);
  await saveState();
  renderChores();
});

el.choreList.addEventListener("change", async (e) => {
  const id = e.target.dataset.toggleChore;
  if (!id) return;
  const item = state.chores.find((c) => c.id === id);
  if (!item) return;
  item.done = !!e.target.checked;
  await saveState();
  renderChores();
  if (state.view === "day") renderCalendar();
});

el.plannerIdeas.addEventListener("click", async (e) => {
  const idx = e.target.dataset.chooseIdea;
  if (idx === undefined) return;
  const idea = state.planner.ideas[Number(idx)];
  if (!idea) return;

  const owner = state.members.find((m) => m.role === "adult") || state.members[0];
  if (!owner) return;

  state.events.push({
    id: uid(),
    title: idea.title || "Date Night",
    startDate: idea.date,
    endDate: idea.date,
    allDay: false,
    start: idea.start_time || "19:00",
    end: idea.end_time || "21:00",
    memberId: owner.id,
    memberName: owner.name,
    involvedMemberIds: state.members.filter((m) => m.role === "adult").map((m) => m.id),
    recurring: "none",
  });

  await saveState();
  renderCalendar();
  renderPersonEvents();
  alert("Date added to calendar.");

  if (state.planner.partnerEmail) {
    alert("Date added to calendar. Email sending is currently disabled.");
  }
});

el.grid.addEventListener("click", (e) => {
  const action = e.target.dataset.action;
  if (action !== "jump") return;
  const date = e.target.dataset.date;
  if (!date) return;
  document.getElementById("eventStartDate").value = date;
  document.getElementById("eventEndDate").value = date;
  document.getElementById("eventTitle").focus();
});

el.grid.addEventListener("change", async (e) => {
  const id = e.target.dataset.toggleChore;
  if (!id) return;
  const c = state.chores.find((x) => x.id === id);
  if (!c) return;
  c.done = !!e.target.checked;
  await saveState();
  renderCalendar();
  renderChores();
});

el.personTabs.addEventListener("click", (e) => {
  const id = e.target.dataset.personId;
  if (!id) return;
  setSelectedPerson(id);
});

el.mainTabs.forEach((b) => {
  b.addEventListener("click", () => setMainTab(b.dataset.tab));
});

document.getElementById("planDateBtn")?.addEventListener("click", () => {});
document.getElementById("prevBtn").addEventListener("click", () => shiftDate(-1));
document.getElementById("nextBtn").addEventListener("click", () => shiftDate(1));
document.getElementById("todayBtn").addEventListener("click", () => {
  state.currentDate = new Date();
  renderCalendar();
});

document.getElementById("shareBtn").addEventListener("click", async () => {
  if (!state.roomId) {
    state.roomId = newRoomId();
    const url = new URL(window.location.href);
    url.searchParams.set("room", state.roomId);
    url.searchParams.delete("data");
    window.history.replaceState({}, "", url.toString());
    await saveState();
    startPolling();
  }

  const link = `${window.location.origin}${window.location.pathname}?room=${encodeURIComponent(state.roomId)}`;
  try {
    await navigator.clipboard.writeText(link);
    alert("Live share link copied.");
  } catch (_err) {
    prompt("Copy this live share link:", link);
  }
});

el.viewBtns.forEach((b) => b.addEventListener("click", () => setView(b.dataset.view)));

function render() {
  setMainTab(state.activeTab, false);
  renderPersonTabs();
  populateMemberSelects();
  renderInvolvedChecklist();
  renderCalendar();
  renderRequests();
  renderRecurring();
  renderMemberList();
  renderPersonEvents();
  renderChores();
  updateChoreNote();
  setPlannerInputs();
  renderPlannerIdeas();
}

(async () => {
  await loadState();
  render();
})();
